image: mcr.microsoft.com/dotnet/sdk:5.0
pipelines:
  branches:
    master:
      - step:
          name: Start
          script:
            - echo "Starting pipeline..."
      - step:
          name: Clean
          script:
            - dotnet clean
      - step:
          name: Build
          script:
            - dotnet build
      - step:
          name: Test
          script:
            - dotnet test