const NAMESPACE = 'redux-users';

export const LOAD_USERS_START = `${NAMESPACE}/LOAD_USERS_START`;
export const LOAD_USERS_SUCCESS = `${NAMESPACE}/LOAD_USERS_SUCCESS`;
export const LOAD_USERS_ERROR = `${NAMESPACE}/LOAD_USERS_ERROR`;
export const CHANGE_PROFILE = `${NAMESPACE}/CHANGE_PROFILE`;
export const CHANGE_EMOTIONAL_STATE = `${NAMESPACE}/CHANGE_EMOTIONAL_STATE`